name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2022]
        config: ["--config bzlmod", ""]

    steps:
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: ${{ runner.os }}- {{ }}bazel

      - name: Test
        run: |
          bazelisk --bazelrc ci.bazelrc test //... ${{matrix.config}}

      - name: Build
        run: |
          bazelisk --bazelrc ci.bazelrc build //... ${{matrix.config}}


  example:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO(#6): Determine why this won't work with windows, github actions
        # seems to ignore the double hyphen. Then uncomment below.
        # os: [ubuntu-18.04, macos-10.15, windows-2022]
        os: [ubuntu-18.04, macos-10.15]
        config: ["--config bzlmod", ""]
        include:
          - os: ubuntu-18.04
            short_os: linux
          - os: macos-10.15
            short_os: macos
          #- os: windows-2022
          #  short_os: windows

    steps:
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: ${{ runner.os }}-bazel

      # TODO: Find out how to make bzlmod build with //distribution/...
      -  run: |
          cd examples/python_deps

      - name: Run example
        run: >
          bazelisk --bazelrc ci.bazelrc run
          @python_${{matrix.short_os}}//:bin/python3
          ${{matrix.config}} -- -c 'print("hello from cipd")'